/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { LanguageCodenames } from '../system/languages.generated.js';
           
            /*
* Type representing codename of 'English (en-US)' language
*/
            export type EnglishEnUSLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "default">;

            /*
* Typeguard for codename of 'English (en-US)' language
*/
            export function isEnglishEnUSLanguageCodename(value: string | undefined | null): value is EnglishEnUSLanguageCodename {
                return typeof value === 'string' && value === ('default' satisfies EnglishEnUSLanguageCodename);
            }
            