/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { LanguageCodenames } from '../system/languages.generated.js';
           
            /*
* Type representing codename of 'German (de-DE)' language
*/
            export type GermanDeDELanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "de-DE">;

            /*
* Typeguard for codename of 'German (de-DE)' language
*/
            export function isGermanDeDELanguageCodename(value: string | undefined | null): value is GermanDeDELanguageCodename {
                return typeof value === 'string' && value === ('de-DE' satisfies GermanDeDELanguageCodename);
            }
            