/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { MetadataSnippet } from '../snippets/metadata-snippet.generated.js';
import type { PersonType } from '../types/person-type.generated.js';
import type { TargetTopicTaxonomyTermCodenames, TargetTopicTaxonomyCodename } from '../taxonomies/target-topic-taxonomy.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Blog Post' type
*/
            export type BlogPostTypeCodename = keyof Pick<Record<TypeCodenames, null>, "blog_post">;

            /*
* Typeguard for codename of 'Blog Post' type
*/
            export function isBlogPostTypeCodename(value: string | undefined | null): value is BlogPostTypeCodename {
                return typeof value === 'string' && value === ('blog_post' satisfies BlogPostTypeCodename);
            }

/*
    * Blog Post
    *
    * Id: 336302c0-0634-4974-b33b-8c7b0469e837
* Codename: blog_post
    */
export type BlogPostType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: 72869e6e-2822-4e81-944a-d90b3148ce4a
* Type: text
* Required: true
    */
                readonly title: Elements.TextElement;

/*
    * Image
    *
    * Codename: image
* Id: 1361b589-f40e-4c4a-b219-62a0f3f5a8c0
* Type: asset
* Required: true
    */
                readonly image: Elements.AssetsElement;

/*
    * Body
    *
    * Codename: body
* Id: e74bc043-0613-4554-8fb5-4d03a42c61a5
* Type: rich_text
* Required: true
    */
                readonly body: Elements.RichTextElement<CoreType>;

/*
    * Target Topic
    *
    * Codename: category
* Id: 68306d0a-613d-4dca-881e-1e62ef0d15b5
* Type: taxonomy
* Required: false
* Taxonomy: blog_type
    */
                readonly category: Elements.TaxonomyElement<TargetTopicTaxonomyTermCodenames, TargetTopicTaxonomyCodename>;

/*
    * Author
    *
    * Codename: author
* Id: 686aee90-0dd5-4f85-9854-1ea084a708fc
* Type: modular_content
* Required: false
* Allowed content types: person
    */
                readonly author: Elements.LinkedItemsElement<PersonType>;

/*
    * URL slug
    *
    * Codename: url_slug
* Id: cfdddb6d-ae75-431b-ac02-af463468d86b
* Type: url_slug
* Required: true
    */
                readonly url_slug: Elements.UrlSlugElement;} & MetadataSnippet, 
BlogPostTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Blog Post
*/
export type BlogPostTypeElementCodenames = 'title' | 'image' | 'body' | 'category' | 'author' | 'metadata__title' | 'metadata__keywords' | 'metadata__description' | 'url_slug';;

/*
    * Type guard for Blog Post
    *
    * Id: 336302c0-0634-4974-b33b-8c7b0469e837
* Codename: blog_post
    */
export function isBlogPostType(item: IContentItem | undefined | null): item is BlogPostType {
                return item?.system.type === ('blog_post' satisfies BlogPostTypeCodename);
            };



            