/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
// import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Deals' type
*/
            export type DealsTypeCodename = keyof Pick<Record<TypeCodenames, null>, "deals">;

            /*
* Typeguard for codename of 'Deals' type
*/
            export function isDealsTypeCodename(value: string | undefined | null): value is DealsTypeCodename {
                return typeof value === 'string' && value === ('deals' satisfies DealsTypeCodename);
            }

/*
    * Deals
    *
    * Id: 0eb2d107-ef25-4862-9210-4dd002a2a486
* Codename: deals
    */
export type DealsType = IContentItem<
{
/*
    * Deal Title
    *
    * Codename: deal_title
* Id: 5f4912f1-1a8c-416f-8700-7ab49bd73ecd
* Type: text
* Required: false
    */
                readonly deal_title: Elements.TextElement;

/*
    * Start
    *
    * Codename: start
* Id: bb809697-f3d9-4c3c-bc80-dca1b8209c7f
* Type: date_time
* Required: false
    */
                readonly start: Elements.DateTimeElement;

/*
    * End
    *
    * Codename: end
* Id: 6c26c958-27e7-4ed4-9150-49971ee5c9cc
* Type: date_time
* Required: false
    */
                readonly end: Elements.DateTimeElement;

/*
    * Body
    *
    * Codename: body
* Id: 089cc36d-1218-4b37-9384-4b449a0a65a4
* Type: text
* Required: false
    */
                readonly body: Elements.TextElement;

/*
    * Deal Image
    *
    * Codename: deal_image
* Id: 84a6e7ec-31af-456b-a6b2-0224a7276fa4
* Type: asset
* Required: false
    */
                readonly deal_image: Elements.AssetsElement;}, 
DealsTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Deals
*/
export type DealsTypeElementCodenames = 'deal_title' | 'start' | 'end' | 'body' | 'deal_image';;

/*
    * Type guard for Deals
    *
    * Id: 0eb2d107-ef25-4862-9210-4dd002a2a486
* Codename: deals
    */
export function isDealsType(item: IContentItem | undefined | null): item is DealsType {
                return item?.system.type === ('deals' satisfies DealsTypeCodename);
            };



            