/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Hero' type
*/
            export type HeroTypeCodename = keyof Pick<Record<TypeCodenames, null>, "hero">;

            /*
* Typeguard for codename of 'Hero' type
*/
            export function isHeroTypeCodename(value: string | undefined | null): value is HeroTypeCodename {
                return typeof value === 'string' && value === ('hero' satisfies HeroTypeCodename);
            }

/*
    * Hero
    *
    * Id: 1f5b45ed-fbde-45e4-a965-dd2954287f17
* Codename: hero
    */
export type HeroType = IContentItem<
{
/*
    * Headline
    *
    * Codename: headline
* Id: b790c2a3-6603-42e9-b3ee-3fa236e17031
* Type: text
* Required: true
    */
                readonly headline: Elements.TextElement;

/*
    * Button Label
    *
    * Codename: button_label
* Id: e566e61c-73f2-41bf-9468-b96b00fae63b
* Type: text
* Required: false
    */
                readonly button_label: Elements.TextElement;

/*
    * Link
    *
    * Codename: link
* Id: 1a8066a1-8199-4d43-9c7b-b829a760b828
* Type: modular_content
* Required: false
    */
                readonly link: Elements.LinkedItemsElement<CoreType>;

/*
    * Hero Image
    *
    * Codename: hero_image
* Id: b1c4e8f0-8c8d-4ade-86c9-7790f99624c4
* Type: asset
* Required: false
    */
                readonly hero_image: Elements.AssetsElement;}, 
HeroTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Hero
*/
export type HeroTypeElementCodenames = 'headline' | 'button_label' | 'link' | 'hero_image';;

/*
    * Type guard for Hero
    *
    * Id: 1f5b45ed-fbde-45e4-a965-dd2954287f17
* Codename: hero
    */
export function isHeroType(item: IContentItem | undefined | null): item is HeroType {
                return item?.system.type === ('hero' satisfies HeroTypeCodename);
            };



            