/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { ArticleType } from '../types/article-type.generated.js';
import type { CallToActionType } from '../types/call-to-action-type.generated.js';
import type { CollectionCodenames } from '../system/collections.generated.js';
// import type { CoreType } from '../system/types.generated.js';
import type { DisclaimerType } from '../types/disclaimer-type.generated.js';
import type { EventType } from '../types/event-type.generated.js';
import type { HeroType } from '../types/hero-type.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { PageType } from '../types/page-type.generated.js';
import type { VideoType } from '../types/video-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Landing Page' type
*/
            export type LandingPageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "landing_page">;

            /*
* Typeguard for codename of 'Landing Page' type
*/
            export function isLandingPageTypeCodename(value: string | undefined | null): value is LandingPageTypeCodename {
                return typeof value === 'string' && value === ('landing_page' satisfies LandingPageTypeCodename);
            }

/*
    * Landing Page
    *
    * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
* Codename: landing_page
    */
export type LandingPageType = IContentItem<
{
/*
    * Heros
    *
    * Codename: heros
* Id: 74dfc479-b074-407d-8d41-fcb74b2d7a7c
* Type: modular_content
* Required: false
* Allowed content types: hero
* Guidelines: Add heros to show up in your hero carousel
    */
                readonly heros: Elements.LinkedItemsElement<HeroType>;

/*
    * Body Copy
    *
    * Codename: body_copy
* Id: 7b9826ff-5cb0-450f-b16a-bd176aed04cf
* Type: rich_text
* Required: false
* Allowed content types: video, disclaimer, call_to_action
    */
                readonly body_copy: Elements.RichTextElement<VideoType | DisclaimerType | CallToActionType>;

/*
    * Featured Content
    *
    * Codename: featured_content
* Id: 38cf004b-3054-43ff-9b7a-f0734b1d35f1
* Type: modular_content
* Required: false
* Allowed content types: event, article, call_to_action
    */
                readonly featured_content: Elements.LinkedItemsElement<EventType | ArticleType | CallToActionType>;

/*
    * Subpages
    *
    * Codename: subpages
* Id: 9d5080db-f2bb-41a1-bcbe-11786ee3a59d
* Type: subpages
* Required: false
* Allowed content types: page
    */
                readonly subpages: Elements.LinkedItemsElement<PageType>;}, 
LandingPageTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Landing Page
*/
export type LandingPageTypeElementCodenames = 'heros' | 'body_copy' | 'featured_content' | 'subpages';;

/*
    * Type guard for Landing Page
    *
    * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
* Codename: landing_page
    */
export function isLandingPageType(item: IContentItem | undefined | null): item is LandingPageType {
                return item?.system.type === ('landing_page' satisfies LandingPageTypeCodename);
            };



            