/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
// import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Recreation' type
*/
            export type RecreationTypeCodename = keyof Pick<Record<TypeCodenames, null>, "recreation">;

            /*
* Typeguard for codename of 'Recreation' type
*/
            export function isRecreationTypeCodename(value: string | undefined | null): value is RecreationTypeCodename {
                return typeof value === 'string' && value === ('recreation' satisfies RecreationTypeCodename);
            }

/*
    * Recreation
    *
    * Id: 42c94fce-315c-48e4-a2af-23cd1b382c0e
* Codename: recreation
    */
export type RecreationType = IContentItem<
Record<string, never>, 
RecreationTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Recreation
*/
export type RecreationTypeElementCodenames = never;

/*
    * Type guard for Recreation
    *
    * Id: 42c94fce-315c-48e4-a2af-23cd1b382c0e
* Codename: recreation
    */
export function isRecreationType(item: IContentItem | undefined | null): item is RecreationType {
                return item?.system.type === ('recreation' satisfies RecreationTypeCodename);
            };



            