/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { WorkflowCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Academic Resources' workflow
*/
            export type AcademicResourcesWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "academic_resources">;

            /*
* Typeguard for codename of 'Academic Resources' workflow
*/
            export function isAcademicResourcesWorkflowCodename(value: string | undefined | null): value is AcademicResourcesWorkflowCodename {
                return typeof value === 'string' && value === ('academic_resources' satisfies AcademicResourcesWorkflowCodename);
            }

            /*
* Array of all workflow step codenames
*/
            export const academicResourcesWorkflowStepCodenames = ['draft_a8b162c', 'translation', 'peer_review', 'reviewed', 'published', 'archived', 'scheduled'] as const;;
           
            /*
* Type representing all workflow step codenames
*/
            export type AcademicResourcesWorkflowStepCodenames = typeof academicResourcesWorkflowStepCodenames[number];;

            /*
* Typeguard for workflow step codename
*/
            export function isAcademicResourcesWorkflowStepCodename(value: string | undefined | null): value is AcademicResourcesWorkflowStepCodenames {
                return typeof value === 'string' && (academicResourcesWorkflowStepCodenames as readonly string[]).includes(value);
            };
            