/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { WorkflowCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'KOA Franchisee Workflow' workflow
*/
            export type KOAFranchiseeWorkflowWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "koa_franchisee_workflow">;

            /*
* Typeguard for codename of 'KOA Franchisee Workflow' workflow
*/
            export function isKOAFranchiseeWorkflowWorkflowCodename(value: string | undefined | null): value is KOAFranchiseeWorkflowWorkflowCodename {
                return typeof value === 'string' && value === ('koa_franchisee_workflow' satisfies KOAFranchiseeWorkflowWorkflowCodename);
            }

            /*
* Array of all workflow step codenames
*/
            export const kOAFranchiseeWorkflowWorkflowStepCodenames = ['draft_5ea3b01', 'published', 'archived', 'scheduled'] as const;;
           
            /*
* Type representing all workflow step codenames
*/
            export type KOAFranchiseeWorkflowWorkflowStepCodenames = typeof kOAFranchiseeWorkflowWorkflowStepCodenames[number];;

            /*
* Typeguard for workflow step codename
*/
            export function isKOAFranchiseeWorkflowWorkflowStepCodename(value: string | undefined | null): value is KOAFranchiseeWorkflowWorkflowStepCodenames {
                return typeof value === 'string' && (kOAFranchiseeWorkflowWorkflowStepCodenames as readonly string[]).includes(value);
            };
            