/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { WorkflowCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'KOA Marketing Content' workflow
*/
            export type KOAMarketingContentWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "koa_marketing_content">;

            /*
* Typeguard for codename of 'KOA Marketing Content' workflow
*/
            export function isKOAMarketingContentWorkflowCodename(value: string | undefined | null): value is KOAMarketingContentWorkflowCodename {
                return typeof value === 'string' && value === ('koa_marketing_content' satisfies KOAMarketingContentWorkflowCodename);
            }

            /*
* Array of all workflow step codenames
*/
            export const kOAMarketingContentWorkflowStepCodenames = ['draft_e0b9cdf', 'content_review', 'marketing_review_e1dd2d1', 'published', 'archived', 'scheduled'] as const;;
           
            /*
* Type representing all workflow step codenames
*/
            export type KOAMarketingContentWorkflowStepCodenames = typeof kOAMarketingContentWorkflowStepCodenames[number];;

            /*
* Typeguard for workflow step codename
*/
            export function isKOAMarketingContentWorkflowStepCodename(value: string | undefined | null): value is KOAMarketingContentWorkflowStepCodenames {
                return typeof value === 'string' && (kOAMarketingContentWorkflowStepCodenames as readonly string[]).includes(value);
            };
            