/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all collection codenames
*/
            export const collectionCodenames = ['south_padre_island', 'rockport___corpus_christi', 'galveston_island', 'texas', 'southwest_region', 'south_region', 'default', 'academic_content', 'patient_resources', 'operations'] as const;;
           
            /*
* Type representing all collection codenames
*/
            export type CollectionCodenames = typeof collectionCodenames[number];;

            /*
* Typeguard for collection codename
*/
            export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
                return typeof value === 'string' && (collectionCodenames as readonly string[]).includes(value);
            };