
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Demo
* Environment: Production
* Id: d89e24b9-c2c4-0153-3e3b-8d8abd406750
* 
* -------------------------------------------------------------------------------
**/

import type { IContentItem, IContentItemElements } from "@kontent-ai/delivery-sdk";
import type {
  ContentTypeCodenames,
  CollectionCodenames,
  LanguageCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames,
} from "./delivery.codenames.ts";

/**
 * Core content type used in favor of default 'IContentItem'
 */
export type CoreContentType<
  TElementCodenames extends string = string,
  TElements extends IContentItemElements<TElementCodenames> = IContentItemElements<TElementCodenames>,
  TContentTypeCodename extends ContentTypeCodenames = ContentTypeCodenames,
> = IContentItem<
  TElements,
  TContentTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

// CoreClientTypes and CoreDeliveryClient are now defined in main.system.generated.ts
