/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all element codenames
*/
            export const elementCodenames = ['title', 'image', 'body', 'category', 'author', 'metadata__title', 'metadata__keywords', 'metadata__description', 'url_slug', 'heros', 'body_copy', 'featured_content', 'subpages', 'name', 'summary', 'description', 'team', 'medical_specialties', 'headline', 'subheadline', 'image_position', 'button_label', 'button_link', 'phone_number', 'email_address', 'address', 'amenities', 'ways_to_stay', 'menu', 'book_now_cta_text', 'book_now_cta_background_image', 'book_now_cta_background_video_link', 'banner_header', 'banner_body', 'banner_image', 'hero_image', 'url', 'start_date', 'end_date', 'event_type', 'event_topic', 'link', 'first_name', 'last_name', 'prefix', 'suffixes', 'biography', 'job_title', 'phone', 'email', 'website', 'deal_title', 'start', 'end', 'why', 'deal_image', 'video_link', 'caption', 'autoplay', 'type', 'recipe_title', 'recipe_description', 'ingredients', 'preparation', 'submitted_by', 'publish_date', 'introduction', 'article_type', 'topics', 'related_articles', 'website_link'] as const;;
           
            /*
* Type representing all element codenames
*/
            export type ElementCodenames = typeof elementCodenames[number];;

            /*
* Typeguard for element codename
*/
            export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
                return typeof value === 'string' && (elementCodenames as readonly string[]).includes(value);
            };