/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all snippet codenames
*/
            export const snippetCodenames = ['metadata'] as const;;
           
            /*
* Type representing all snippet codenames
*/
            export type SnippetCodenames = typeof snippetCodenames[number];;

            /*
* Typeguard for snippet codename
*/
            export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
                return typeof value === 'string' && (snippetCodenames as readonly string[]).includes(value);
            };