/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all taxonomy codenames
*/
            export const taxonomyCodenames = ['article_type', 'amenities', 'blog_type', 'koa_regions', 'event_type', 'ways_to_stay', 'event_topic'] as const;;
           
            /*
* Type representing all taxonomy codenames
*/
            export type TaxonomyCodenames = typeof taxonomyCodenames[number];;

            /*
* Typeguard for taxonomy codename
*/
            export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
                return typeof value === 'string' && (taxonomyCodenames as readonly string[]).includes(value);
            };