/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { BlogPostType } from '../types/blog-post-type.generated.js';
import type { LandingPageType } from '../types/landing-page-type.generated.js';
import type { ServiceType } from '../types/service-type.generated.js';
import type { CallToActionType } from '../types/call-to-action-type.generated.js';
import type { RecreationType } from '../types/recreation-type.generated.js';
import type { CampgroundType } from '../types/campground-type.generated.js';
import type { PageType } from '../types/page-type.generated.js';
import type { EventType } from '../types/event-type.generated.js';
import type { PersonType } from '../types/person-type.generated.js';
import type { HeroType } from '../types/hero-type.generated.js';
import type { DealsType } from '../types/deals-type.generated.js';
import type { VideoType } from '../types/video-type.generated.js';
import type { DisclaimerType } from '../types/disclaimer-type.generated.js';
import type { RecipeType } from '../types/recipe-type.generated.js';
import type { ArticleType } from '../types/article-type.generated.js';
import type { AttractionType } from '../types/attraction-type.generated.js';

            /*
* Array of all type codenames
*/
            export const typeCodenames = ['blog_post', 'landing_page', 'service', 'call_to_action', 'recreation', 'campground', 'page', 'event', 'person', 'hero', 'deals', 'video', 'disclaimer', 'recipe', 'article', 'attraction'] as const;;
           
            /*
* Type representing all type codenames
*/
            export type TypeCodenames = typeof typeCodenames[number];;

            /*
* Typeguard for type codename
*/
            export function isTypeCodename(value: string | undefined | null): value is TypeCodenames {
                return typeof value === 'string' && (typeCodenames as readonly string[]).includes(value);
            };

					 /*
* Core content type with narrowed types. Use this instead of'IContentItem' for increased type safety.
*/
					 export type CoreType = BlogPostType | LandingPageType | ServiceType | CallToActionType | RecreationType | CampgroundType | PageType | EventType | PersonType | HeroType | DealsType | VideoType | DisclaimerType | RecipeType | ArticleType | AttractionType

					/*
* Type mapping for codename & type. Can be used for type safe access to type based on the codename of type.
*/
					export type CodenameTypeMapping = {
	readonly blog_post: BlogPostType,
readonly landing_page: LandingPageType,
readonly service: ServiceType,
readonly call_to_action: CallToActionType,
readonly recreation: RecreationType,
readonly campground: CampgroundType,
readonly page: PageType,
readonly event: EventType,
readonly person: PersonType,
readonly hero: HeroType,
readonly deals: DealsType,
readonly video: VideoType,
readonly disclaimer: DisclaimerType,
readonly recipe: RecipeType,
readonly article: ArticleType,
readonly attraction: AttractionType,
};

					/*
* Helper type that returns type based on the codename of type.
*/
					export type CodenameTypeMapper<TTypeCodename extends TypeCodenames> = TTypeCodename extends keyof CodenameTypeMapping ? CodenameTypeMapping[TTypeCodename] : CoreType;
					