/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all workflow codenames
*/
            export const workflowCodenames = ['default', 'koa_franchisee_workflow', 'patient_resources', 'academic_resources', 'koa_marketing_content', 'biographies'] as const;;
           
            /*
* Type representing all workflow codenames
*/
            export type WorkflowCodenames = typeof workflowCodenames[number];;

            /*
* Typeguard for workflow codename
*/
            export function isWorkflowCodename(value: string | undefined | null): value is WorkflowCodenames {
                return typeof value === 'string' && (workflowCodenames as readonly string[]).includes(value);
            };

            /*
* Array of all workflow codenames
*/
            export const workflowStepCodenames = ['draft', 'copy_review', 'published', 'archived', 'scheduled', 'draft_5ea3b01', 'draft_b242d4d', 'medical_review', 'legal_review', 'marketing_review', 'draft_a8b162c', 'translation', 'peer_review', 'reviewed', 'draft_e0b9cdf', 'content_review', 'marketing_review_e1dd2d1', 'draft_97d445e', 'staff_member_review', 'reviewed_1778942'] as const;;
           
            /*
* Type representing all workflow codenames
*/
            export type WorkflowStepCodenames = typeof workflowStepCodenames[number];;

            /*
* Typeguard for workflow codename
*/
            export function isWorkflowStepCodename(value: string | undefined | null): value is WorkflowStepCodenames {
                return typeof value === 'string' && (workflowStepCodenames as readonly string[]).includes(value);
            };