/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Amenities' taxonomy
*/
            export type AmenitiesTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "amenities">;

            /*
* Typeguard for codename of 'Amenities' taxonomy
*/
            export function isAmenitiesTaxonomyCodename(value: string | undefined | null): value is AmenitiesTaxonomyCodename {
                return typeof value === 'string' && value === ('amenities' satisfies AmenitiesTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const amenitiesTaxonomyTermCodenames = ['swimming_pool', 'cable_tv', 'wi_fi', 'snack_bar', 'bike_rental', 'firewood', 'fishing', 'hot_tub_sauna', 'kamping_kitching', 'mini_golf', 'pavilion', 'propane', 'tours_shuttle', 'rv_rentals'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type AmenitiesTaxonomyTermCodenames = typeof amenitiesTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isAmenitiesTaxonomyTermCodename(value: string | undefined | null): value is AmenitiesTaxonomyTermCodenames {
                return typeof value === 'string' && (amenitiesTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            