/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Article Type' taxonomy
*/
            export type ArticleTypeTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "article_type">;

            /*
* Typeguard for codename of 'Article Type' taxonomy
*/
            export function isArticleTypeTaxonomyCodename(value: string | undefined | null): value is ArticleTypeTaxonomyCodename {
                return typeof value === 'string' && value === ('article_type' satisfies ArticleTypeTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const articleTypeTaxonomyTermCodenames = ['research', 'clinical_guidelines', 'industry_updates'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type ArticleTypeTaxonomyTermCodenames = typeof articleTypeTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isArticleTypeTaxonomyTermCodename(value: string | undefined | null): value is ArticleTypeTaxonomyTermCodenames {
                return typeof value === 'string' && (articleTypeTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            