/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'KOA Regions' taxonomy
*/
            export type KOARegionsTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "koa_regions">;

            /*
* Typeguard for codename of 'KOA Regions' taxonomy
*/
            export function isKOARegionsTaxonomyCodename(value: string | undefined | null): value is KOARegionsTaxonomyCodename {
                return typeof value === 'string' && value === ('koa_regions' satisfies KOARegionsTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const kOARegionsTaxonomyTermCodenames = ['alaskan', 'midwest', 'northeast', 'n__rockies_plains', 'northwest', 'south', 'southeast', 'southwest', 'upper_midwest', 'west'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type KOARegionsTaxonomyTermCodenames = typeof kOARegionsTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isKOARegionsTaxonomyTermCodename(value: string | undefined | null): value is KOARegionsTaxonomyTermCodenames {
                return typeof value === 'string' && (kOARegionsTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            