/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Target Topic' taxonomy
*/
            export type TargetTopicTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "blog_type">;

            /*
* Typeguard for codename of 'Target Topic' taxonomy
*/
            export function isTargetTopicTaxonomyCodename(value: string | undefined | null): value is TargetTopicTaxonomyCodename {
                return typeof value === 'string' && value === ('blog_type' satisfies TargetTopicTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const targetTopicTaxonomyTermCodenames = ['rv_advice', 'plan', 'activities', 'cook', 'trips'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type TargetTopicTaxonomyTermCodenames = typeof targetTopicTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isTargetTopicTaxonomyTermCodename(value: string | undefined | null): value is TargetTopicTaxonomyTermCodenames {
                return typeof value === 'string' && (targetTopicTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            