/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TaxonomyCodenames } from '../system/taxonomies.generated.js';
           
            /*
* Type representing codename of 'Ways to Stay' taxonomy
*/
            export type WaysToStayTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "ways_to_stay">;

            /*
* Typeguard for codename of 'Ways to Stay' taxonomy
*/
            export function isWaysToStayTaxonomyCodename(value: string | undefined | null): value is WaysToStayTaxonomyCodename {
                return typeof value === 'string' && value === ('ways_to_stay' satisfies WaysToStayTaxonomyCodename);
            }

            /*
* Array of all taxonomy term codenames
*/
            export const waysToStayTaxonomyTermCodenames = ['rv_sites', 'lodging', 'tent_sites', 'extended_stays', 'groups', 'glamping', 'unique_lodging'] as const;;
           
            /*
* Type representing all taxonomy term codenames
*/
            export type WaysToStayTaxonomyTermCodenames = typeof waysToStayTaxonomyTermCodenames[number];;

            /*
* Typeguard for taxonomy term codename
*/
            export function isWaysToStayTaxonomyTermCodename(value: string | undefined | null): value is WaysToStayTaxonomyTermCodenames {
                return typeof value === 'string' && (waysToStayTaxonomyTermCodenames as readonly string[]).includes(value);
            };
            