/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Austin East' collection
*/
            export type AustinEastCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "texas">;

            /*
* Typeguard for codename of 'Austin East' collection
*/
            export function isAustinEastCollectionCodename(value: string | undefined | null): value is AustinEastCollectionCodename {
                return typeof value === 'string' && value === ('texas' satisfies AustinEastCollectionCodename);
            }
            