/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Customer Service' collection
*/
            export type CustomerServiceCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "patient_resources">;

            /*
* Typeguard for codename of 'Customer Service' collection
*/
            export function isCustomerServiceCollectionCodename(value: string | undefined | null): value is CustomerServiceCollectionCodename {
                return typeof value === 'string' && value === ('patient_resources' satisfies CustomerServiceCollectionCodename);
            }
            