/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Galveston Island' collection
*/
            export type GalvestonIslandCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "galveston_island">;

            /*
* Typeguard for codename of 'Galveston Island' collection
*/
            export function isGalvestonIslandCollectionCodename(value: string | undefined | null): value is GalvestonIslandCollectionCodename {
                return typeof value === 'string' && value === ('galveston_island' satisfies GalvestonIslandCollectionCodename);
            }
            