/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Leander / NW Austin' collection
*/
            export type LeanderNWAustinCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "southwest_region">;

            /*
* Typeguard for codename of 'Leander / NW Austin' collection
*/
            export function isLeanderNWAustinCollectionCodename(value: string | undefined | null): value is LeanderNWAustinCollectionCodename {
                return typeof value === 'string' && value === ('southwest_region' satisfies LeanderNWAustinCollectionCodename);
            }
            