/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Marketing' collection
*/
            export type MarketingCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "academic_content">;

            /*
* Typeguard for codename of 'Marketing' collection
*/
            export function isMarketingCollectionCodename(value: string | undefined | null): value is MarketingCollectionCodename {
                return typeof value === 'string' && value === ('academic_content' satisfies MarketingCollectionCodename);
            }
            