/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Ozark / Fort Rucker' collection
*/
            export type OzarkFortRuckerCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "south_region">;

            /*
* Typeguard for codename of 'Ozark / Fort Rucker' collection
*/
            export function isOzarkFortRuckerCollectionCodename(value: string | undefined | null): value is OzarkFortRuckerCollectionCodename {
                return typeof value === 'string' && value === ('south_region' satisfies OzarkFortRuckerCollectionCodename);
            }
            