/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Rockport / Corpus Christi' collection
*/
            export type RockportCorpusChristiCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "rockport___corpus_christi">;

            /*
* Typeguard for codename of 'Rockport / Corpus Christi' collection
*/
            export function isRockportCorpusChristiCollectionCodename(value: string | undefined | null): value is RockportCorpusChristiCollectionCodename {
                return typeof value === 'string' && value === ('rockport___corpus_christi' satisfies RockportCorpusChristiCollectionCodename);
            }
            