/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: KOA 
 * Environment: Production
 * Id: 8381787f-717e-007f-809d-a80af690508b
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'South Padre Island' collection
*/
            export type SouthPadreIslandCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "south_padre_island">;

            /*
* Typeguard for codename of 'South Padre Island' collection
*/
            export function isSouthPadreIslandCollectionCodename(value: string | undefined | null): value is SouthPadreIslandCollectionCodename {
                return typeof value === 'string' && value === ('south_padre_island' satisfies SouthPadreIslandCollectionCodename);
            }
            